glmmTMB/glmmTMB

glmmTMB/src/glmmTMB.cpp

I think ```dbetabinom``` returned the *negative* log-density, so I have flipped all signs (and re-arranged a bit to make it closer to wikipedia formula). Someone please double check (Anders?).

Fix typo in betabinomial distribution

---

glmmTMB/inst/tests/test-basics.R

Changed 2 tests to reflect that `fixef` now returns a list.
Basic Binomial CBPP examples were failing.
```
> test_that("Basic Binomial CBPP examples", {
+     expect_is(gm0, "glmmTMB")
+     expect_is(gm1, "glmmTMB")
+     expect_equal(fixef(gm0)[[1]], c("(Intercept)" = -2.053136), tolerance = .0005)
+     expect_equal(fixef(gm1)[[1]], c("(Intercept)" = -1.3928024,
+                                period2 = -0.9976629, period3 = -1.1337828,
+                                period4 = -1.5865186),
+                   tolerance = .001) # <- TODO: lower eventually
+ })
Error: Test failed: 'Basic Binomial CBPP examples'
* Not expected: fixef(gm0)[[1]] not equal to c(`(Intercept)` = -2.053136)
-2.05 - -2.05 == -0.00697.
* Not expected: fixef(gm1)[[1]] not equal to c(`(Intercept)` = -1.3928024, …
```

edit test-basics.R to use new model form and compare to lme4 results

---

glmmTMB/DESCRIPTION

Old versions of TMB will still work with this update. The change only affects the CRAN version.

Add RcppEigen as dependency

---

glmmTMB/R/predict.R

Tested that
```
example(glmmTMB)
predict(fm3,newdata=sleepstudy)
```
works after change.

Fix broken predict method

---

glmmTMB/R/VarCorr.R

Small bug with surprisingly large impact...
Before fix:
```
x <- rnorm(1e3)
y <- rnorm(1e3)+x
fit <- glmmTMB(y~x,se=TRUE)
system.time(print(fit))
user  system elapsed 
47.838   0.016  47.906
```
After fix:
```
system.time(print(fit))
user  system elapsed 
0.01    0.00    0.01
```

Fix usesDispersion() in VarCorr.glmmTMB()

---

glmmTMB/R/glmmTMB.R
glmmTMB/src/glmmTMB.cpp
tmptest/ar1.R

Doesn't break anything and works on a test example :)
PROS:
- Simple to implement: re-uses lme4 machinery completely ==> consistent with other structs: diag, cs, us.
CONS:
- Not yet capable of using irregular times although this feature is implemented in the cpp template.
- Syntax may seem a bit odd: ```ar1(DaysFac + 0 | Subject)``` and not ~~```ar1(Days | Subject)```~~.
- Not as efficient as could be if e.g. different 'Subjects' have very different 'Days'.

First shot at AR1 formula interface

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/src/glmmTMB.cpp

- ADREPORT should not be enabled by default. Can now run large datasets.
- glmmTMB: Don't call sdreport twice.
- Eliminate compiler warning.

Some optimizations:

---

.travis.yml
glmmTMB/R/utils.R
glmmTMB/man/epil2.Rd

All this does is to add a standard travis set up  (from  https://github.com/metacran/r-builder ).  Right now we're passing on release and devel but *not* on oldrel builds .... can probably fix oldrel build but it might be a little bit of a nuisance ...

new attempt at travis setup

---

glmmTMB/R/glmmTMB.R

This commit solves #194. 
TODO:
- Add test that updating from `nbinom` to `poisson` and back to `nbinom` does not change the fit (even if the nbinom uses a non-trivial `dispformula`).

Fix dispformula

---

glmmTMB/R/methods.R
glmmTMB/src/glmmTMB.cpp

This is a continuation of branch 'simulate_truncated' that now also simulates 'b' and 'bzi' vectors.
Truncated simulators are correct as far as I can tell - still need testing.

Simulate from random effects

---

glmmTMB/R/predict.R
glmmTMB/tests/testthat/test-predict.R

* Add checks to guard against invalid predictions #222.
* Enable the predict argument `allow.new.levels=FALSE`. By default a warning is thrown if predicting new levels.

predict.glmmTMB updates

---

glmmTMB/R/methods.R

When running the tweedie example in `glmmTMB/tests/testthat/test-families.R` the power parameter is now displayed:
```
> twm
Formula:          y ~ 1
AIC       BIC    logLik  df.resid 
10064.246 10081.049 -5029.123      1997 
Number of obs: 2000
Overdispersion parameter for tweedie family (): 2.04 
Tweedie power parameter:  1.7 
Fixed Effects:
Conditional model:
(Intercept)  
1.405  
```
Not sure this is the 'right way'. Please check carefully and modify :)

Print Tweedie power parameter

---

glmmTMB/R/methods.R
glmmTMB/man/confint.glmmTMB.Rd
glmmTMB/tests/testthat/test-methods.R

I'm not sure this is necessary/a good idea.  There was some confusion on my part: the `broom.mixed` method for tidying `glmmTMB` objects was using "Wald" rather than "wald". Don't know whether we should allow this sloppiness, change the default to "Wald" (which is what `lme4` uses), or leave it as is.

allow method="[Ww]ald" in confint.glmmTMB

---

glmmTMB/src/glmmTMB.cpp

Fixes a warning that will occur when clang 7.0.0 is released http://www.stats.ox.ac.uk/pub/bdr/clang7/glmmTMB.out
I confirmed that `test-predict.R` includes `predict(...type="conditional")` which should check that predictions are not affected by this change.

removed mu=mu in predict uncorrected_zipredictcode

---

glmmTMB/R/methods.R
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-families.R
glmmTMB/tests/testthat/test-methods.R
glmmTMB/tests/testthat/test-reml.R

this PR addresses https://github.com/glmmTMB/glmmTMB/issues/396 ; it also loosens some test tolerances (anticipating possible changes in lme4 that change numeric outcomes slightly), and adds some extra labels to some of the exotic-family tests

Ranef 2grp fix

---

glmmTMB/tests/testthat/test-families.R

fixes #397. The compois test data are underdipsersed enough and far enough above zero that they can also be used for the truncated_compois test.

shortened truncated_compois test

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/R/utils.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-predict.R
glmmTMB/tests/testthat/test-reml.R

This is (1) not heavily tested and (2) not as elegant as I'd like (see especially `fix_predvars` in `utils.R` ... using `append()` would make it *slightly* nicer, but it still uses `all.vars()` in  a fairly crude way ... but this seems like an important bug.  Comments and more extensive test cases welcome!

preliminary fix for data-dependent bases

---

glmmTMB/vignettes/mcmc.rmd

- Wrapping `knitr::read_chunk` in order to force this in current R environment
Reference for fix: https://github.com/yihui/knitr/issues/1647

Fixing MCMC vignette with workaround for knitr function

---

Makefile
glmmTMB/NAMESPACE
glmmTMB/R/Anova.R
glmmTMB/R/effects.R
glmmTMB/R/emmeans.R

attempt to fix method exports as specified [here](https://stat.ethz.ch/pipermail/r-package-devel/2019q1/003331.html).  So far have been unable to reproduce the error in the unfixed (master) version even with `_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE` ...

Downstream methods fix

---

.travis.yml

Upgrade Travis to use Ubuntu Xenial along with newer versions of compilers to be able to use OMP properly

Xenial and newer compilers in Travis

---

glmmTMB/R/glmmTMB.R
glmmTMB/man/glmmTMB.Rd
glmmTMB/man/mkTMBStruc.Rd
glmmTMB/tests/testthat/test-start.R

This allows the user to specify starting values.
I think it's fairly harmless; the only open question I can think of is whether we'd rather make `start` an additional top-level parameter to `glmmTMB`, or whether it should instead be included as part of `glmmTMBControl`  (`lme4` has it as a top-level parameter).

add 'start' parameter

---

glmmTMB/R/predict.R
glmmTMB/man/predict.glmmTMB.Rd
glmmTMB/tests/testthat/test-predict.R

This could certainly be extended to try to allow a full `re.form` specification (i.e., use particular REs and ignore others), but to do that we would need a robust way to map from a RE formula to a vector specifying which `theta` values to map to -100 (or whatever).

pop-level prediction

---

glmmTMB/R/emmeans.R
glmmTMB/R/zzz.R

I have modified the emmeans support to be marginally better (I hope). Changes include:
1. Removing `.std.link.labels()` -- this is exported by **emmeans**
2. Dynamically registering the methods. See added file `zzz.R` which uses a utility provided in the **emmeans** package
3. Trying to do a better job supporting the `zi` and `disp` components. I'm not sure I have this exactly right, but these components have different link functions than the conditional model, which is what was provided before.
*Note:* I was unable to test the rebuilt package because my system can't do the compilation right. However, I did test the methods by putting them in my workspace.

Changes to emmeans support

---

glmmTMB/DESCRIPTION

Hi glmmTMB maintainers 👋 ,
The URL in the `DESCRIPTION` file points to the glmmTMB account and not the package repo.

Correct URL to point to GitHub repo

---

.github/workflows/R-CMD-check.yaml

Changes use of `working-directory` and tweaks arguments to some steps to support checking the package in its subfolder

Fix path issues in R-CMD-check action

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/utils.R

`Matrix::sparseMatrix` args will be changing in an upcoming version, leading to lots of warnings (`giveCSparse` is deprecated in favour of `repr="T"`). This version (which preserves back-compatibility) may be overkill, we could also wait until the new version is out and impose a package version dependency ...

update null-matrix args for Matrix update

---

glmmTMB/R/predict.R

We could also fix this problem by mandating R >= 4.0.2, but the adjustment to the code needed to avoid this bug is fairly trivial.
https://stackoverflow.com/questions/67229026/failing-to-produce-glmmtmb-diagnostics-plots-with-packages-performance-and-dharm

change order of on.exit to accommodate bug in R <4.0.2

---

glmmTMB/R/predict.R
glmmTMB/tests/testthat/test-predict.R

I discovered a fairly trivial/unimportant logic error (`predict(..., re.form=NA, fast=FALSE)` should be allowed but isn't)

correct error structure for fast=TRUE + re.form=NA

---

glmmTMB/R/glmmTMB.R

I see `make test` failing because of (new?) complex eigenvalue check. Note that `Jacobian(gr, par)` will result in un-symmetric result 'at random' so `e_complex_check()` is sort of pointless IMO.
✖ |  30 1     | fitting exotic families [12.4 s]                                                                                                                                                            
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-families.R:199:5): dbetabinom
Error: detected complex eigenvalues of covariance matrix (max(abs(Im))=1.13473e-10: try se=FALSE?
Backtrace:
1. base::suppressWarnings(...) …

Make hessian symmetric

---

glmmTMB/vignettes/model_evaluation.Rnw

This PR finally solves #651. It is required to build the vignettes.

Chunk eval=TRUE to avoid using loaded object

---

glmmTMB/man/Owls.Rd
glmmTMB/man/Salamanders.Rd

`check --as-cran` was giving this message
```
Found the following URLs which should use \doi (with the DOI name only):
File ‘Owls.Rd’:
https://doi.org/10.1016/j.anbehav.2007.01.027
File ‘Salamanders.Rd’:
http://dx.doi.org/10.1111/1365-2664.12585
http://dx.doi.org/10.5061/dryad.5m8f6
```
So I guess this is what they want.

changed data citation urls to dois

---

README.md
glmmTMB/inst/NEWS.Rd
glmmTMB/vignettes/parallel.Rmd

Fix 'invalid' URLS from NOTEs in last R CMD check. Noted here: https://github.com/glmmTMB/glmmTMB/issues/647#issuecomment-866910497

Correct 'invalid' URLS #647

---

glmmTMB/src/utils.cpp

I *think* this addresses #751, although I'm not quite sure how we can test on clang 13.0 ...

put omp.h include before R includes

---

glmmTMB/R/methods.R

It might occasionally be useful to print the dispersion parameter as a fixed effects table even when it is only a single intercept. I added an option to print.fixef.glmmTMB to do so.

add an option to print trivial dispersion coef tables

---

glmmTMB/DESCRIPTION
glmmTMB/R/diagnose.R
glmmTMB/R/methods.R
glmmTMB/man/diagnose.Rd

fixed a long-standing bug in vcov(full=TRUE) (would only have useful names if there was  <= 1 RE component); improved `diagnose()` messages etc.
The troubleshooting vignette could probably still use some love (and `NEWS` file not updated for fix above).

Vcov names fix

---

glmmTMB/NAMESPACE
glmmTMB/R/glmmTMB.R
glmmTMB/man/dot-checkRankX.Rd
glmmTMB/man/glmmTMBControl.Rd
glmmTMB/tests/testthat/test-checkRank.R

this fixes a bug in `glmmTMBControl(rank_check = "adjust")` (wasn't skipping empty matrices) and does a little bit of extra cleanup (option is now "warning" rather than "warn" so we can automatically `get()` the appropriate action). Also adds some tests.
Advances #830 (but should probably still be kept open, further room for improvement)

improve/test 'rank_check="adjust"' option

---

glmmTMB/DESCRIPTION
glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/downstream_methods.Rd
glmmTMB/man/glmmTMBControl.Rd
glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-checkRank.R
glmmTMB/tests/testthat/test-predict.R

I think this fixes the last issue highlighted in #873 (it took some rearranging ...)
Also cleans up a few warnings thrown by `test-checkRank` tests

fix log_nzprob for non-fast predictions

---

glmmTMB/R/family.R
glmmTMB/inst/CITATION
glmmTMB/man/nbinom2.Rd
glmmTMB/vignettes/glmmTMB.Rnw
glmmTMB/vignettes/glmmTMB.bib

Hi All,
Among the `R CMD check --as-cran` notes that I was seeing (I'm running R 4.1.3 on Debian 11) were:
```
Found the following (possibly) invalid URLs:
https://doi.org/https://doi.org/10.1111/2041-210X.12236
URL: https://doi.org/https://doi.org/10.1111/2041-210X.12236
From: inst/doc/covstruct.html
Status: 503
Message: Service Unavailable
URL: https://doi.org/https://doi.org/10.1111/2041-210X.13303
From: inst/doc/covstruct.html
Status: 503
Message: Service Unavailable
```
This seems like a valid note, since we don't want `https://doi.org` to appear twice in the same URL. To fix this problem, I edited `glmmTMB.bib` to change entries
```
doi = {https://doi.org/10.1111/2041-210X.13303},
doi = {https://doi.org/10.1111/2041-210X.12236},
```
to
```
doi = {10.1111/2041-210X.13303},
doi = …
```

Use short DOI instead of expanded URL

---

glmmTMB/DESCRIPTION
glmmTMB/R/emmeans.R
glmmTMB/man/confint.glmmTMB.Rd
glmmTMB/man/downstream_methods.Rd
glmmTMB/vignettes/model_evaluation.Rnw

This PR adds my improved version of **emmeans** support discussed in #887 
Instead of the separate `component` and `mode` arguments I presented there, I decided to just add two more options to `component`: `"response"` and `"cmean"`. These correspond to `type = "response"` and `type = "conditional"` in `predict.glmmTMB`.
I expanded the examples in one of the vignettes, in part to illustrate and explain the confusing thing that happens with hurdle models.
Another note: In the examples, I added `withAutoprint()` in a couple of places, because otherwise we see only the *last* set of results when we run the examples.

Enhanced emmeans support and vignette addition

---

glmmTMB/R/glmmTMB.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-basics.R

Maybe we can sneak this into the next release, since it's minor

drop dims from single-column matrix responses

---

glmmTMB/src/glmmTMB.cpp
misc/simcode.R

Incorporated code to allow simulation with different conditions for the b  values (ie, random effect variable). Implemented this for  AR1, US, OU, and RR covariance structures.
1.  simulate with fixed 'b' values
2.  'b' values set to zero, or 
3.  estimate b values randomly

Extend re form

---

glmmTMB/R/glmmTMB.R

Remove the warnings which are from internal model fits.

Remove warnings from the models which are used in the start method for rr random effects

---

glmmTMB/R/family.R
glmmTMB/R/glmmTMB.R
glmmTMB/R/utils.R
glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-basics.R
glmmTMB/tests/testthat/test-families.R
misc/neg_binom_ex.R

The initial inspiration for this was to fix the problem in #988 (which was ultimately about the user having negative values in a two-column binomial response variable, but getting a confusing error). This also adds improved checking for negative or non-integer response values in count and binomial-type families.

Check neg binom vals

---

glmmTMB/DESCRIPTION
glmmTMB/R/enum.R
glmmTMB/R/utils.R
glmmTMB/man/get_cor.Rd
glmmTMB/tests/testthat/test-utils.R
glmmTMB/vignettes/covstruct.rmd
glmmTMB/vignettes/sim.rmd

utilities for translating between `theta` and unstructured correlation matrices (bidirectional); the corr-to-theta direction (`put_cor`) was buggy. I needed an LDL decomposition, so this now depends on the fastmatrix package (which has no further dependencies). If we wanted to avoid that there are some suggestions in comments in the code ...
Also highlighted these functions better in the covstruct and sim vignettes.

fix/improve get_cor, put_cor

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/methods.R
glmmTMB/R/predict.R
glmmTMB/R/profile.R
glmmTMB/R/utils.R
glmmTMB/inst/misc/test_parallel.R
glmmTMB/man/glmmTMBControl.Rd
glmmTMB/man/omp_check.Rd
glmmTMB/tests/testthat/test-basics.R
glmmTMB/tests/testthat/test-control.R

This allows users to take advantage of the new autopar stuff in TMB (in particular, to allow parallelization with rr models).
* might need to update TMB dependence to a newer version (although this *might* still work even with older TMB versions -- haven't tested)
* this *should* be harmless to include in a new release, but I might wait until after the next CRAN-mandated release just to give ourselves a bit more time
* at the moment `autopar = FALSE` is the default, which I think makes sense until we have more info. For example, this test shows that for a simple example non-autopar is slightly faster than autopar (with an even bigger advantage for larger N ...)
* may need to worry about the (unlikely) event that glmmTMB has been compiled/installed using CppAD rather than (default) TMBAd? …

modify parallel to allow autopar

---

glmmTMB/R/glmmTMB.R

with the export of formula processing to `reformulas`, we need to work a little harder to make sure that the list of known 'specials' (covariance structures etc.) is passed to the formula-processing functions. As far as I can tell this handles all the required cases. 
This should resolve https://github.com/glmmTMB/glmmTMB/issues/1069, https://github.com/bbolker/reformulas/issues/2
It's a little bit annoying to test because it involves adding new covariance structures to the code and seeing if they are recognized properly.

pass known covstructs to reformulas fns

---

glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-VarCorr.R

This one is pretty straightforward; we forgot to update the C++ to `REPORT()` some quantities, broke `VarCorr()`

make sure to REPORT corrdisp, sddisp (GH #1058)

---

glmmTMB/R/glmmTMB.R
misc/smooth_issues.R

This is preliminary/to soon to actually merge, but it is now possible to extract information on which indices of `beta` and `b` correspond to each smooth term in a model:
```r
devtools::load_all("glmmTMB")
data("Nile")
ndat <- data.frame(time = c(time(Nile)), val = c(Nile))
sm1 <- glmmTMB(val ~ s(time, bs = "tp"), data = ndat,
REML = TRUE, start = list(theta = 5))
lapply(sm1$modelInfo$reTrms,
\(y) lapply(y$smooth_info, \(x) x$re$beta_ind))
lapply(sm1$modelInfo$reTrms,
\(y) lapply(y$smooth_info, \(x) x$re$b_ind))
```
This should probably be built into a `getME()` option ... (and possibly we should simultaneously set up the ability to extract `b_ind` for *any* RE term, or any component of a RE term, which will help with the `extend_re_form` branch ...)

Save smooth info

---

glmmTMB/R/profile.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-methods.R

This was a very small change (add `include_nonest = FALSE` to a `vcov()` call)

profiling models with mapped parameters

---

glmmTMB/R/diagnose.R
glmmTMB/R/methods.R
glmmTMB/R/utils.R
glmmTMB/tests/testthat/test-diagnose.R
glmmTMB/tests/testthat/test-mapequal.R
glmmTMB/tests/testthat/test-methods.R

Resolves #1120, and cleans up a bunch of other messy stuff with mapped parameters + `vcov()`

Map diagnose

---

glmmTMB/R/family.R
glmmTMB/tests/testthat/test-families.R

I think this should be OK, but I am mildly nervous about squeezing it into the upcoming release because it does change user-visible behaviour ... on the other hand it would be a shame to leave it out ... (not sure why the issues only become apparent when calling `effect::Effect()`, but that's part of the mystery of delayed evaluation ...)
Maybe we can merge this and then run reverse-dependency checks again ... ??

more careful evaluation of  family component (fix #1133)

---

glmmTMB/vignettes/mcmc.rmd

I moved things around so that the DIY sampler is contained in one section. I also added a little more about where to look at `tmbstan` documetnation.

make it possible to skip DIY sampler

---

glmmTMB/R/enum.R
glmmTMB/R/glmmTMB.R
glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-varstruc.R
glmmTMB/vignettes/covstruct.rmd

The homogeneous compound-symmetric structure can also be achieved by using `map`, but having it available as a built-in structure is easier for users [they don't have to know as much about the underlying structure of the `theta` parameter vector/understand how `map=` works].

add homcs cov structure; covstruct vignette tweaks

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/methods.R
glmmTMB/inst/NEWS.Rd

see #1156 
headline now looks like this (fourth element labeled "-2*log(L)" instead of "deviance")
```
AIC       BIC    logLik -2*log(L)  df.resid 
35026.72  35059.50 -17508.36  35016.72      5195 
```

update 'deviance' to '-2*log(L)' in output

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/man/dot-checkRankX.Rd
glmmTMB/tests/testthat/test-predict.R
glmmTMB/tests/testthat/test-priors.R

Fixes #1146, I think.
This could conceivably add a tiny bit of overhead because we now have to check for `NA` values in FE model matrices (it might? be possible to avoid this by skipping rank-checking/adjustment when prediction is being done?)

Rankdefprior2

---

glmmTMB/tests/testthat/test-downstream.R

E-mail from Russ Lenth reporting that one of the downstream tests of `emmeans::joint_tests()` had failed (tolerance was previously set to 1e-5, test was failing with a relative difference of 1.5e-5, increased tolerance to 2e-5 ...)

loosen downstream emmeans test tolerance slightly

---

glmmTMB/R/methods.R
glmmTMB/R/utils.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-methods.R

This is  a bit of an edge case (`confint()` applied to a model with a random effect in dispersion), but it should be pretty harmless - can we squeeze it into the version we're about to release?

Notheta ci

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-predict.R

Fixes problem reported in https://stackoverflow.com/q/77517125/190277  (rank-deficient columns were breaking prediction machinery because we attempted to drop them even though they get dropped in a preceding step)
Incidentally also fixes a problem caused by the development version of `reformulas` (no longer exports a `head.language` method ...

Rankdef pred
