README.md
inputOutput.md

start document descriging expected input and output from code chunks
fixed typo

more discussion details

---

glmmTMB/src/glmmTMB.cpp

- Rename families
- Add links
- Add cov structs
- Input stuff

Re-worked cpp file

---

glmmTMB/R/methods.R

- getME() update " a la lme4 "

---

glmmTMB/R/VarCorr.R
glmmTMB/tests/testthat/test-disp.R

also added a test for dispformula

fixed VarCor with RE in zi

---

glmmTMB/R/VarCorr.R
glmmTMB/R/glmmTMB.R
glmmTMB/R/methods.R
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-families.R
glmmTMB/tests/testthat/test-saveload.R

This pull request fixes #177 *and* a bug in reported variances and correlations.

Fix varcorr 2nd try

---

glmmTMB/DESCRIPTION
glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/R/utils.R
glmmTMB/tests/testthat/test-families.R
glmmTMB/tests/testthat/test-methods.R

fixed the issues Mollie identified with predict. Cleaned up a bit of the formula manipulation code.

Bolker fixpred

---

glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-families.R

Fix truncated distributions with zero observations.

Fix truncated

---

glmmTMB/R/glmmTMB.R
glmmTMB/tests/testthat/test-env.R

Dispformula

---

glmmTMB/R/family.R
glmmTMB/R/glmmTMB.R
glmmTMB/R/methods.R
glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-families.R
glmmTMB/tests/testthat/test-methods.R

Continuing #260 and #259 with similar changes for the betabinomial family.

Betabinomial

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/utils.R
glmmTMB/tests/testthat/test-methods.R
glmmTMB/tests/testthat/test-offset.R

(for now, until we implement them ...)

throw error if offset included in zi/disp formula

---

glmmTMB/R/VarCorr.R
glmmTMB/inst/NEWS.Rd
glmmTMB/inst/test_data/glmmTMB-test-funs.R
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-varstruc.R

Bbolker printar1 fix

---

glmmTMB/R/glmmTMB.R
glmmTMB/tests/testthat/test-predict.R

Fix predict

---

glmmTMB/DESCRIPTION
glmmTMB/R/VarCorr.R

Following [advice from Martin ](https://stat.ethz.ch/pipermail/r-devel/2018-March/075737.html)

remove deprecated rBind; add depend R 3.2.0

---

glmmTMB/DESCRIPTION

This should remove a warning about the undeclared package dependency.

suggest plyr

---

glmmTMB/R/VarCorr.R
glmmTMB/vignettes/sim.rmd

Fix zi RE summarize

---

glmmTMB/R/predict.R
glmmTMB/R/utils.R
glmmTMB/man/predict.glmmTMB.Rd
glmmTMB/tests/testthat/test-methods.R
glmmTMB/tests/testthat/test-predict.R

this is still ugly but handles all the cases I've thrown at it so far.  Deserves to be deeply refactored but I can't do that right now (volunteers?).  Added some code comments and some vague warnings in the documentation.  Should resolve #421 ...

improving (?) predict for complex bases

---

glmmTMB/R/VarCorr.R
glmmTMB/R/family.R
glmmTMB/man/nbinom2.Rd
glmmTMB/man/sigma.glmmTMB.Rd

Tweedie doc

---

glmmTMB/R/family.R
glmmTMB/man/nbinom2.Rd

citation for mean-parameterized compois

---

glmmTMB/DESCRIPTION

require effects pkg >=4.0-1

---

glmmTMB/DESCRIPTION

I'll probably go ahead and merge this myself soon since it seems trivial/harmless ... based on [this twitter exchange](https://twitter.com/tjmahr/status/1113185464490569733)

bump TMB version (needed for tmbroot)

---

glmmTMB/vignettes/parallel.Rmd

- remove dependency on data.table
- be careful not to use more cores than available.

work on parallel vignette

---

glmmTMB/R/predict.R
glmmTMB/man/predict.glmmTMB.Rd

documentation fixes only. Fix #491

clarify pop-level prediction

---

glmmTMB/R/utils.R
glmmTMB/tests/testthat/test-predict.R

this might want to be tested/exercised more, but is in any case any improvement/fix for the reported bug (no NEWS entry yet)

tests for predicting I(x^2); fixes #512

---

glmmTMB/DESCRIPTION
glmmTMB/NAMESPACE
glmmTMB/R/family.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/formFuns.Rd
glmmTMB/man/nbinom2.Rd
glmmTMB/tests/testthat/test-zi.R

rename hacked Gamma to ziGamma; docs

---

glmmTMB/R/emmeans.R
glmmTMB/tests/testthat/test-downstream.R

Added the tests you requested, and they run. Also was able to build after I reconfigured build tools. I think I was trying to build in the wrong directory.

Added emmeans tests

---

glmmTMB/R/enum.R
glmmTMB/R/predict.R
glmmTMB/man/predict.glmmTMB.Rd
glmmTMB/src/glmmTMB.cpp
glmmTMB/tests/testthat/test-disp.R
glmmTMB/tests/testthat/test-predict.R

Dispersion predict

---

.gitignore
glmmTMB/DESCRIPTION
glmmTMB/R/Anova.R
glmmTMB/R/emmeans.R
glmmTMB/man/confint.glmmTMB.Rd
glmmTMB/man/downstream_methods.Rd
glmmTMB/man/fbx.Rd
glmmTMB/man/formatVC.Rd
glmmTMB/man/formula.glmmTMB.Rd
glmmTMB/man/getME.glmmTMB.Rd
glmmTMB/man/glmmTMB.Rd
glmmTMB/man/glmmTMB_methods.Rd
glmmTMB/man/mkTMBStruc.Rd
glmmTMB/man/predict.glmmTMB.Rd
glmmTMB/man/print.VarCorr.glmmTMB.Rd
glmmTMB/man/profile.glmmTMB.Rd
glmmTMB/man/ranef.glmmTMB.Rd
glmmTMB/man/splitForm.Rd
glmmTMB/tests/testthat/test-downstream.R
glmmTMB/vignettes/model_evaluation.Rnw

an attempt to pass tests on windows-oldversion

downstream stuff conditional on car/Anova versions

---

glmmTMB/R/emmeans.R
glmmTMB/man/downstream_methods.Rd
glmmTMB/tests/testthat/test-downstream.R
glmmTMB/vignettes/model_evaluation.Rnw

attempt to condition tests based on what downstream methods are actually available ...

work around variation in downstream methods exports

---

glmmTMB/vignettes/covstruct.rmd

Covstruct vignette

---

glmmTMB/R/utils.R
glmmTMB/tests/testthat/test-utils.R

make noSpecials work with one-sided formulas; add tests

---

glmmTMB/DESCRIPTION
glmmTMB/R/family.R
glmmTMB/man/nbinom2.Rd

add trunc nbinom2 variance

---

glmmTMB/R/family.R
glmmTMB/R/utils.R
glmmTMB/man/formFuns.Rd
glmmTMB/man/nbinom2.Rd
glmmTMB/tests/testthat/test-predict.R
glmmTMB/tests/testthat/test-utils.R

Offset form fix

---

.gitignore
glmmTMB/R/glmmTMB.R
glmmTMB/man/getReStruc.Rd
glmmTMB/tests/testthat/test-varstruc.R

store terms information, check that ar1() time is a factor

---

glmmTMB/R/methods.R
glmmTMB/tests/testthat/test-methods.R

Confint fix

---

glmmTMB/R/VarCorr.R
glmmTMB/R/methods.R
glmmTMB/inst/doc/troubleshooting.html
glmmTMB/man/sigma.glmmTMB.Rd
glmmTMB/tests/testthat/test-methods.R

I didn't change `./misc/salamanders.rmd` because it's part of the R Journal publication. I changed `./glmmTMB/inst/doc/troubleshooting.html`, but not the files underlying it.

Change "Overdispersion" to "Dispersion"

---

glmmTMB/R/Anova.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/downstream_methods.Rd
glmmTMB/tests/testthat/test-Anova.R
glmmTMB/tests/testthat/test-downstream.R

This fixes a simple typo/omission in the type-3 Anova method that made zi Anova break in some conditions

Zi anova fix

---

glmmTMB/R/methods.R
glmmTMB/R/utils.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/downstream_methods.Rd
glmmTMB/man/vcov.glmmTMB.Rd
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-basics.R
glmmTMB/tests/testthat/test-mapopt.R

This is slightly backward-incompatible (summaries for mapped variables will  have NA rather than zero in the standard error and subsequent columns), but that seems like a bug fix to me ...
This handles mapped variables more consistently. Not guaranteeing I've found all of the edge cases, but several things that weren't working are working now ... (fixes #678)

Map params

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/predict.R
glmmTMB/src/init.h
glmmTMB/src/utils.cpp

Fixes #714
Passing checks (on Windows) `test-families.R` and `test-rr.R`.
Tested for `glmmTMB.cores` 1 and 4.

Windows openmp2

---

glmmTMB/src/glmmTMB.cpp

resolve float/int ambiguity for Solaris

cast in pow() for solaris

---

glmmTMB/R/methods.R

make ranef() method more flexible

---

glmmTMB/DESCRIPTION
glmmTMB/R/methods.R
glmmTMB/R/utils.R

this is to improve compatibility with `broom.mixed` (and generally seems useful).

Ignore stuff

---

glmmTMB/R/glmmTMB.R
glmmTMB/man/glmmTMB.Rd

improve na.action documentation, remove bogus na.fail default

---

Makefile
glmmTMB/DESCRIPTION
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-sparseX.R

loosen test for Solaris (#732)

---

glmmTMB/DESCRIPTION
glmmTMB/R/methods.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/formfuns.Rd
glmmTMB/man/residuals.glmmTMB.Rd
glmmTMB/tests/testthat/test-methods.R

add working residuals

---

glmmTMB/R/emmeans.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-VarCorr.R
glmmTMB/tests/testthat/test-downstream.R

Emmeans fix

---

glmmTMB/R/predict.R
glmmTMB/man/predict.glmmTMB.Rd

This would permit computation of custom contrasts of predicted values (e.g., each treatment vs control).

Add cov.fit argument to predict() method

---

glmmTMB/R/predict.R
glmmTMB/R/utils.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-predict.R

I think this is OK, may want to wait for confirmation from issues authors (#632, #845, #853).  More test cases would be good. If we feel sufficiently confident we could also consider this to resolve #70  ...

More predvars

---

glmmTMB/src/glmmTMB.cpp

bugfix: forgot to initialize 'log_nzprob' vector

---

glmmTMB/R/predict.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-predict.R

tests for @kaskr's segfault fix, and add a warning for unused args in `predict()`

Test nzprobfix

---

glmmTMB/R/glmmTMB.R
glmmTMB/tests/testthat/test-families.R
glmmTMB/tests/testthat/test-methods.R
glmmTMB/vignettes/hacking.rmd

Sorry @mebrooks , one last-minute fix and a little bit for the vignette: merge please?

Deviance resids

---

glmmTMB/R/predict.R
glmmTMB/tests/testthat/test-predict.R

Reform pred na

---

glmmTMB/man/glmmTMB.Rd
glmmTMB/src/glmmTMB.cpp
misc/ordbeta.R
misc/sim.R

Would be good to have some proper tests, but basic tests ([here](https://github.com/glmmTMB/glmmTMB/blob/ordbeta_sim/misc/ordbeta.R)) look OK ...

ordbeta sim method

---

glmmTMB/R/methods.R
glmmTMB/inst/NEWS.Rd
glmmTMB/man/getME.glmmTMB.Rd

This is a fairly trivial change, may be worth merging before release (should add to NEWS though ...)

add 'b' to set of objects retrievable by getME

---

glmmTMB/DESCRIPTION

Update R requirement in DESCRIPTION

---

glmmTMB/R/priors.R
glmmTMB/man/priors.Rd

Partial matching issue in priors documentation

---

glmmTMB/vignettes/priors.rmd

Inconsistency in priors vignette

---

glmmTMB/R/glmmTMB.R
glmmTMB/R/priors.R
glmmTMB/tests/testthat/test-priors.R

Error in printing `summary()` information on priors

---

glmmTMB/R/glmmTMB.R
glmmTMB/tests/testthat/test-smooths.R

miscellaneous bugs encountered while trying to redo an analysis previously done with `gamm4` ...

fix smooths with zero fixed-effect columns

---

glmmTMB/R/methods.R
glmmTMB/tests/testthat/test-methods.R

fix Pearson resids for non-trivial dispersion (fix #1053)

---

glmmTMB/R/glmmTMB.R
glmmTMB/tests/testthat/test-smooths.R

fix X col names for multiple smooths

---

glmmTMB/R/methods.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-predict.R

Fix pearson resids

---

glmmTMB/R/utils.R
glmmTMB/man/get_cor.Rd
glmmTMB/man/simulate_new.Rd
glmmTMB/vignettes/covstruct.rmd

improve simulate_new docs

---

Makefile
glmmTMB/R/utils.R

Should (?) be more graceful with use of add-on packages that include glmmTMB ...

autopar check specifies DLL

---

glmmTMB/R/predict.R
glmmTMB/inst/NEWS.Rd
glmmTMB/tests/testthat/test-predict.R

fixes #1197.  Spent some time thinking about how to deal with contrast mismatches between prediction data and new data: decided that warning was sufficient (contrasts in new data will be ignored ...)

Predict contrast fix

---

glmmTMB/DESCRIPTION
glmmTMB/R/glmmTMB.R
misc/ar_mem.R

Contributes to solution of #995.  Bumps `reformulas` requirement to 0.4.1.

Reformulas sparse

---

glmmTMB/tests/testthat/test-smooths.R
notes/smooths.rmd

Fix ts inclusion
